FinancialAppDemo/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinancialAppDemo.Models;

namespace FinancialAppDemo.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CategoryController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Category
        public async Task<IActionResult> Index()
        {
              return _context.Categories != null ? 
                          View(await _context.Categories
                          .OrderBy(x => x.Title)
                          .ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
        }

        // GET: Category/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Category/Create
        public IActionResult Create()
        {
            return View(new Category());
        }

        // POST: Category/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,Title,Icon,Type")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,Title,Icon,Type")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

FinancialAppDemo/Controllers/DashboardController.cs
using FinancialAppDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Linq;
using System.Collections.Generic;

namespace FinancialAppDemo.Controllers
{
    public class DashboardController : Controller
    {

        private readonly ApplicationDbContext _context;

        public DashboardController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // to get last 7 days transactions

            DateTime StartDate = DateTime.Today.AddDays(-6);
            DateTime EndDate = DateTime.Today;

            ViewBag.StartDate = StartDate.ToString("dd-MMM-yy (ddd)");
            ViewBag.EndDate = EndDate.ToString("dd-MMM-yy (ddd)");

            List<Transaction> SelectedTransactions = await _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.Date >= StartDate && y.Date <= EndDate)
                .ToListAsync();


            // total income
            double TotalIncome = SelectedTransactions
                .Where(a => a.Category.Type == "Income")
                .Sum(b => b.Amount);
            ViewBag.TotalIncome = TotalIncome.ToString("C2");

            // total expense
            double TotalExpense = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .Sum(j => j.Amount);
            ViewBag.TotalExpense = TotalExpense.ToString("C2");

            // balance
            double Balance = TotalIncome - TotalExpense;
            ViewBag.Balance = Balance.ToString("C2");

            // Data for Doughnut chart - Expense by category
            ViewBag.DoughnutChart = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Category.CategoryId)
                .Select(z => new
                {
                    categoryTitleWithIcon = z.First().CategoryWithIcon,
                    amount = z.Sum(y => y.Amount),
                    formattedAmount = z.Sum(y => y.Amount).ToString("C0")
                })
                .OrderByDescending(l=>l.amount)
                .ToList();

            // Data for Dashline chart - Income vs Expense
            // Income
            List<LineChartData> IncomeSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Income")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Income = k.Sum(l => l.Amount)
                })
                .ToList();

            // Expense
            List<LineChartData> ExpenseSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Expense = k.Sum(l => l.Amount)
                })
                .ToList();

            //Combine both income and expense as an object
            string[] Last7Days = new string[7];
            for (int i = 0; i < 7; i++)
            {
                Last7Days[i] = StartDate.AddDays(i).ToString("dd-MMM") + ' ' + StartDate.AddDays(i).DayOfWeek.ToString();
                Last7Days[i] = StartDate.AddDays(i).ToString("dd-MMM (ddd)");
            };
            // LinQ method:
            //string[] last7Days = Enumerable.Range(0, 7)
            //    .Select(i => StartDate.AddDays(i).ToString("dd-MMM"))
            //    .ToArray();

            //LinQ
            ViewBag.LineChartData = from day in Last7Days
                                    join Income in IncomeSummary on day equals Income.Day into dayIncomeJoined
                                    from Income in dayIncomeJoined.DefaultIfEmpty()
                                    join Expense in ExpenseSummary on day equals Expense.Day into expenseJoined
                                    from Expense in expenseJoined.DefaultIfEmpty()
                                    select new
                                    {
                                        Day = day,
                                        Income = Income == null ? 0 : Income.Income,
                                        Expense = Expense == null ? 0 : Expense.Expense,
                                    };

            // Recent Transaction
            List<Transaction> RecentList = new List<Transaction>();
            var TotalTransaction = await _context.Transactions.OrderByDescending(x => x.Date).ToListAsync();
            for (int i = 0; i < 6; i++) 
            {
                RecentList.Add(TotalTransaction[i]);
            }
            ViewBag.RecentTransaction = RecentList;

            // Highest transaction (using Linq)
            ViewBag.HighestTransaction = await _context.Transactions
                .Where(y => y.Category.Type == "Expense" && y.Date >= StartDate && y.Date <= EndDate)
                .OrderByDescending(x => x.Amount)
                .Include(x => x.Category)
                .Take(6)
                .ToListAsync();

            return View(new DashboardViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Index(DashboardViewModel dashboardViewModel)
        {
            // to get last 7 days transactions
            //DateTime StartDate = DateTime.Today.AddDays(-6);
            //DateTime EndDate = DateTime.Today;

            DateTime StartDate = dashboardViewModel.StartDate;
            DateTime EndDate = dashboardViewModel.EndDate;

            ViewBag.StartDate = StartDate.ToString("dd-MMM-yy (ddd)");
            ViewBag.EndDate = EndDate.ToString("dd-MMM-yy (ddd)");

            List<Transaction> SelectedTransactions = await _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.Date >= StartDate && y.Date <= EndDate)
                .ToListAsync();


            // total income
            double TotalIncome = SelectedTransactions
                .Where(a => a.Category.Type == "Income")
                .Sum(b => b.Amount);
            ViewBag.TotalIncome = TotalIncome.ToString("C2");

            // total expense
            double TotalExpense = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .Sum(j => j.Amount);
            ViewBag.TotalExpense = TotalExpense.ToString("C2");

            // balance
            double Balance = TotalIncome - TotalExpense;
            ViewBag.Balance = Balance.ToString("C2");

            // Data for Doughnut chart - Expense by category
            ViewBag.DoughnutChart = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Category.CategoryId)
                .Select(z => new
                {
                    categoryTitleWithIcon = z.First().CategoryWithIcon,
                    amount = z.Sum(y => y.Amount),
                    formattedAmount = z.Sum(y => y.Amount).ToString("C0")
                })
                .OrderByDescending(l => l.amount)
                .ToList();

            // Data for Dashline chart - Income vs Expense
            // Income
            List<LineChartData> IncomeSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Income")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Income = k.Sum(l => l.Amount)
                })
                .ToList();

            // Expense
            List<LineChartData> ExpenseSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Expense = k.Sum(l => l.Amount)
                })
                .ToList();

            //Combine both income and expense as an object
            string[] Last7Days = new string[7];
            for (int i = 0; i < 7; i++)
            {
                Last7Days[i] = StartDate.AddDays(i).ToString("dd-MMM (ddd)");
            };
            // LinQ method:
            //string[] last7Days = Enumerable.Range(0, 7)
            //    .Select(i => StartDate.AddDays(i).ToString("dd-MMM"))
            //    .ToArray();

            //LinQ
            ViewBag.LineChartData = from day in Last7Days
                                    join Income in IncomeSummary on day equals Income.Day into dayIncomeJoined
                                    from Income in dayIncomeJoined.DefaultIfEmpty()
                                    join Expense in ExpenseSummary on day equals Expense.Day into expenseJoined
                                    from Expense in expenseJoined.DefaultIfEmpty()
                                    select new
                                    {
                                        Day = day,
                                        Income = Income == null ? 0 : Income.Income,
                                        Expense = Expense == null ? 0 : Expense.Expense,
                                    };

            // Recent Transaction
            List<Transaction> RecentList = new List<Transaction>();

FinancialAppDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Financial Tracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="	https://cdn.syncfusion.com/ej2/20.2.43/bootstrap5-dark.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@300;700&family=Press+Start+2P&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FinancialAppDemo.styles.css" asp-append-version="true" />
    <script src="https://cdn.syncfusion.com/ej2/20.2.43/dist/ej2.min.js"></script>
</head>
<body class="e-bigger">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm box-shadow mb-1" id="layout-nav-bar">
            <div class="container-xxl">
                <!--For home page-->
                @if (ViewData["isExpenseTrackerApp"] == null)
                {
                    <a class="navbar-brand fw-bolder text-secondary fs-4" href="#home-sidebar" data-bs-toggle="offcanvas"
                       role="button" aria-controls="sidebar"><i class="fa-solid fa-spinner fa-pulse"></i> Readme</a>                 
                }

                <!--For expense tracker-->
                @if (ViewData["isHomePage"] == null)
                {
                    <div class="dropdown mt-3">
                        <button class="btn dropdown-toggle bg-opacity-100 text-white" type="button" id="expense-dropdown"
                            data-bs-toggle="dropdown">
                            <i class="fa-solid fa-sliders"></i> Navigate
                        </button>
                        <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="projects-dropdown">
                            <li><a class="dropdown-item" asp-controller="Dashboard" asp-action="Index">Dashboard</a></li>
                            <li><a class="dropdown-item" asp-controller="Transaction" asp-action="Index">Transaction</a></li>
                            <li><a class="dropdown-item" asp-controller="Category" asp-action="Index">Category</a></li>
                        </ul>
                    </div>
                }

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" 
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon">
                        <i class="bi bi-chevron-bar-down" style="color:#fff; font-size:28px;"></i>
                    </span>
                </button>
                <div class="navbar-collapse collapse justify-content-end">
                    <ul class="navbar-nav text-center">
                        <li class="nav-item">
                            <a class="nav-link text-light fw-light" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-house"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light fw-light"><i class="bi bi-bell"></i></a>
                        </li>
                        <li class="nav-item d-md-none">
                            <a class="nav-link text-light fw-light" href="#">Login</a>
                        </li>
                        <li class="nav-item ms-2 d-none d-md-inline align-self-center">
                            <a class="btn btn-dark text-light" href="#">Login</a>
                        </li>
                        <li class="nav-item nav-link text-light fw-light">
                            <a href="#about-me" class="d-md-none">
                                About Me
                            </a>
                        </li>
                    </ul>
                    <a href="#about-me" class="d-none d-md-inline">
                        @*<img src="/image/programmercut.jpg" class="profile-pic ms-3" />*@
                        <img src="~/image/my_pic_full_cut.jpg" class=" profile-pic ms-3" />
                    </a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container mt-5">
        <div class="row justify-content-evenly">
            <div class="col-md-10">
                <main role="main" class="pb-3">
                    <!--to hide breadcumb at home page-->
                    @if (ViewData["isHomePage"] == null) 
                    { 
                        <div class="row">
                            <div class="col-md-7">
                                <div class="d-flex flex-column mb-3">
                                    <ejs-breadcrumb id="breadcrumb" separatorTemplate="@Html.Raw("<span class='fa-solid fa-angle-right'></span>")"></ejs-breadcrumb>
                                </div>
                            </div>
                        </div>
                    }
                    @RenderBody()
                </main>
            </div>
        </div>
    </div>

 @*   <footer class="border-top footer text-muted">
        <div class="container-fluid">
            &copy; 2022 - Projects
        </div>
    </footer>*@

    <!--Offcanvas: Home-->
    <div class="offcanvas offcanvas-start" data-bs-scroll="true" tabindex="-1" id="home-sidebar" aria-labelledby="sidebar-label">
        <div class="offcanvas-header">
            <h3 class="offcanvas-title text-black" id="sidebar-label"><strong>ReadMe</strong></h3>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
            <p class="text-black">Simple Web Application that contains multiple projects.</p>
            <!--Dropdown button-->
            <div class="dropdown mt-3">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="projects-dropdown" 
                data-bs-toggle="dropdown">Choose a project</button>
                <ul class="dropdown-menu" aria-labelledby="projects-dropdown">
                    <li><a class="dropdown-item" asp-action="ToDoList">To Do List</a></li>
                    <li><a class="dropdown-item" asp-controller="Category" asp-action="Index">Expenses Tracker</a></li>
                    <li><a class="dropdown-item" asp-controller="Home" asp-action="GuessNum">Guess The Number</a></li>
                    <li><a class="dropdown-item" asp-controller="Home" asp-action="PigGame">Pig Game</a></li>
                </ul>
            </div>
        </div>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
    <ejs-scripts></ejs-scripts>
</body>
</html>

FinancialAppDemo/Views/Shared/_PigGameLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/PigGame.css" asp-append-version="true" />
    <title>Guess My Number!</title>
</head>

<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/js/PigGame.js" asp-append-version="true"></script>
</body>
</html>

FinancialAppDemo/Views/Shared/_ToDoListLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="/css/todolist.css" />
    <title>To-do-list</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    <script src="/js/todolist.js"></script>
</body>
</html>

FinancialAppDemo/Views/Shared/_guessNumLayout.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/guessNum.css" asp-append-version="true" />
    <title>Guess My Number!</title>
</head>

<body>
    <div>
        @RenderBody()
    </div>
    <script src="~/js/guessNum.js" asp-append-version="true"></script>
</body>
</html>