FinancialAppDemo/Models/DashboardViewModel.cs
using System.ComponentModel.DataAnnotations;


namespace FinancialAppDemo.Models
{
    public class DashboardViewModel
    {
        public DateTime StartDate { get; set; } = DateTime.Today.AddDays(-6);

        public DateTime EndDate { get; set; } = DateTime.Today;
    }
}

FinancialAppDemo/Controllers/DashboardController.cs
using FinancialAppDemo.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Syncfusion.EJ2.Linq;
using System.Collections.Generic;

namespace FinancialAppDemo.Controllers
{
    public class DashboardController : Controller
    {

        private readonly ApplicationDbContext _context;

        public DashboardController(ApplicationDbContext context)
        {
            _context = context;
        }
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            // to get last 7 days transactions

            DateTime StartDate = DateTime.Today.AddDays(-6);
            DateTime EndDate = DateTime.Today;

            ViewBag.StartDate = StartDate.ToString("dd-MMM-yy (ddd)");
            ViewBag.EndDate = EndDate.ToString("dd-MMM-yy (ddd)");

            List<Transaction> SelectedTransactions = await _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.Date >= StartDate && y.Date <= EndDate)
                .ToListAsync();


            // total income
            double TotalIncome = SelectedTransactions
                .Where(a => a.Category.Type == "Income")
                .Sum(b => b.Amount);
            ViewBag.TotalIncome = TotalIncome.ToString("C2");

            // total expense
            double TotalExpense = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .Sum(j => j.Amount);
            ViewBag.TotalExpense = TotalExpense.ToString("C2");

            // balance
            double Balance = TotalIncome - TotalExpense;
            ViewBag.Balance = Balance.ToString("C2");

            // Data for Doughnut chart - Expense by category
            ViewBag.DoughnutChart = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Category.CategoryId)
                .Select(z => new
                {
                    categoryTitleWithIcon = z.First().CategoryWithIcon,
                    amount = z.Sum(y => y.Amount),
                    formattedAmount = z.Sum(y => y.Amount).ToString("C0")
                })
                .OrderByDescending(l=>l.amount)
                .ToList();

            // Data for Dashline chart - Income vs Expense
            // Income
            List<LineChartData> IncomeSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Income")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Income = k.Sum(l => l.Amount)
                })
                .ToList();

            // Expense
            List<LineChartData> ExpenseSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Expense = k.Sum(l => l.Amount)
                })
                .ToList();

            //Combine both income and expense as an object
            string[] Last7Days = new string[7];
            for (int i = 0; i < 7; i++)
            {
                Last7Days[i] = StartDate.AddDays(i).ToString("dd-MMM") + ' ' + StartDate.AddDays(i).DayOfWeek.ToString();
                Last7Days[i] = StartDate.AddDays(i).ToString("dd-MMM (ddd)");
            };
            // LinQ method:
            //string[] last7Days = Enumerable.Range(0, 7)
            //    .Select(i => StartDate.AddDays(i).ToString("dd-MMM"))
            //    .ToArray();

            //LinQ
            ViewBag.LineChartData = from day in Last7Days
                                    join Income in IncomeSummary on day equals Income.Day into dayIncomeJoined
                                    from Income in dayIncomeJoined.DefaultIfEmpty()
                                    join Expense in ExpenseSummary on day equals Expense.Day into expenseJoined
                                    from Expense in expenseJoined.DefaultIfEmpty()
                                    select new
                                    {
                                        Day = day,
                                        Income = Income == null ? 0 : Income.Income,
                                        Expense = Expense == null ? 0 : Expense.Expense,
                                    };

            // Recent Transaction
            List<Transaction> RecentList = new List<Transaction>();
            var TotalTransaction = await _context.Transactions.OrderByDescending(x => x.Date).ToListAsync();
            for (int i = 0; i < 6; i++) 
            {
                RecentList.Add(TotalTransaction[i]);
            }
            ViewBag.RecentTransaction = RecentList;

            // Highest transaction (using Linq)
            ViewBag.HighestTransaction = await _context.Transactions
                .Where(y => y.Category.Type == "Expense" && y.Date >= StartDate && y.Date <= EndDate)
                .OrderByDescending(x => x.Amount)
                .Include(x => x.Category)
                .Take(6)
                .ToListAsync();

            return View(new DashboardViewModel());
        }

        [HttpPost]
        public async Task<IActionResult> Index(DashboardViewModel dashboardViewModel)
        {
            // to get last 7 days transactions
            //DateTime StartDate = DateTime.Today.AddDays(-6);
            //DateTime EndDate = DateTime.Today;

            DateTime StartDate = dashboardViewModel.StartDate;
            DateTime EndDate = dashboardViewModel.EndDate;

            ViewBag.StartDate = StartDate.ToString("dd-MMM-yy (ddd)");
            ViewBag.EndDate = EndDate.ToString("dd-MMM-yy (ddd)");

            List<Transaction> SelectedTransactions = await _context.Transactions
                .Include(x => x.Category)
                .Where(y => y.Date >= StartDate && y.Date <= EndDate)
                .ToListAsync();


            // total income
            double TotalIncome = SelectedTransactions
                .Where(a => a.Category.Type == "Income")
                .Sum(b => b.Amount);
            ViewBag.TotalIncome = TotalIncome.ToString("C2");

            // total expense
            double TotalExpense = SelectedTransactions
                .Where(i => i.Category.Type == "Expense")
                .Sum(j => j.Amount);
            ViewBag.TotalExpense = TotalExpense.ToString("C2");

            // balance
            double Balance = TotalIncome - TotalExpense;
            ViewBag.Balance = Balance.ToString("C2");

            // Data for Doughnut chart - Expense by category
            ViewBag.DoughnutChart = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Category.CategoryId)
                .Select(z => new
                {
                    categoryTitleWithIcon = z.First().CategoryWithIcon,
                    amount = z.Sum(y => y.Amount),
                    formattedAmount = z.Sum(y => y.Amount).ToString("C0")
                })
                .OrderByDescending(l => l.amount)
                .ToList();

            // Data for Dashline chart - Income vs Expense
            // Income
            List<LineChartData> IncomeSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Income")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Income = k.Sum(l => l.Amount)
                })
                .ToList();

            // Expense
            List<LineChartData> ExpenseSummary = SelectedTransactions
                .Where(x => x.Category.Type == "Expense")
                .GroupBy(y => y.Date)
                .Select(k => new LineChartData()
                {
                    //Day = k.First().Date.ToString("dd-MMM") + ' ' + k.First().Date.DayOfWeek.ToString(),
                    Day = k.First().Date.ToString("dd-MMM (ddd)"),
                    Expense = k.Sum(l => l.Amount)
                })
                .ToList();

            //Combine both income and expense as an object
            string[] Last7Days = new string[7];
            for (int i = 0; i < 7; i++)
            {
                Last7Days[i] = StartDate.AddDays(i).ToString("dd-MMM (ddd)");
            };
            // LinQ method:
            //string[] last7Days = Enumerable.Range(0, 7)
            //    .Select(i => StartDate.AddDays(i).ToString("dd-MMM"))
            //    .ToArray();

            //LinQ
            ViewBag.LineChartData = from day in Last7Days
                                    join Income in IncomeSummary on day equals Income.Day into dayIncomeJoined
                                    from Income in dayIncomeJoined.DefaultIfEmpty()
                                    join Expense in ExpenseSummary on day equals Expense.Day into expenseJoined
                                    from Expense in expenseJoined.DefaultIfEmpty()
                                    select new
                                    {
                                        Day = day,
                                        Income = Income == null ? 0 : Income.Income,
                                        Expense = Expense == null ? 0 : Expense.Expense,
                                    };

            // Recent Transaction
            List<Transaction> RecentList = new List<Transaction>();

FinancialAppDemo/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinancialAppDemo.Models;

namespace FinancialAppDemo.Controllers
{
    public class TransactionController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TransactionController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Transaction
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Transactions.
                Include(t => t.Category)
                .OrderByDescending(y => y.Date);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Transaction/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Transactions == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Category)
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // GET: Transaction/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories.OrderBy(x => x.Title), "CategoryId", "TitleWithIconWithType");
            return View();
        }

        // POST: Transaction/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TransactionId,CategoryId,Amount,Details,Date")] Transaction transaction)
        {
            if (ModelState.IsValid)
            {
                _context.Add(transaction);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Icon", transaction.CategoryId);
            return View(transaction);
        }

        // GET: Transaction/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Transactions == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "TitleWithIconWithType", transaction.CategoryId);
            return View(transaction);
        }

        // POST: Transaction/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TransactionId,CategoryId,Amount,Details,Date")] Transaction transaction)
        {
            if (id != transaction.TransactionId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(transaction);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TransactionExists(transaction.TransactionId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CategoryId", "Icon", transaction.CategoryId);
            return View(transaction);
        }

        // GET: Transaction/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Transactions == null)
            {
                return NotFound();
            }

            var transaction = await _context.Transactions
                .Include(t => t.Category)
                .FirstOrDefaultAsync(m => m.TransactionId == id);
            if (transaction == null)
            {
                return NotFound();
            }

            return View(transaction);
        }

        // POST: Transaction/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Transactions == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Transactions'  is null.");
            }
            var transaction = await _context.Transactions.FindAsync(id);
            if (transaction != null)
            {
                _context.Transactions.Remove(transaction);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TransactionExists(int id)
        {
          return (_context.Transactions?.Any(e => e.TransactionId == id)).GetValueOrDefault();
        }
    }
}

FinancialAppDemo/Views/Dashboard/Index.cshtml
@model DashboardViewModel

@{
    ViewData["isExpenseTrackerApp"] = true;
}

@*Summary Widget*@
<div class="row mb-4">
    <div class="col-md-4">
        <div class="d-flex flex-row widget summary income">
            <div class="d-flex flex-column justify-content-center p-5">
                <i class="fa-solid fa-dollar-sign fa-2xl"></i>
            </div>
            <div class="d-flex flex-column m-auto py-3">
                <span class="lead">Total Income</span>
                <h1 class="display-6">@ViewBag.TotalIncome</h1>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="d-flex flex-row widget summary expense">
            <div class="d-flex flex-column justify-content-center p-5">
                <i class="fa-solid fa-dollar-sign fa-2xl"></i>
            </div>
            <div class="d-flex flex-column m-auto py-3">
                <span class="lead">Total Expense</span>
                <h1 class="display-6">@ViewBag.TotalExpense</h1>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="d-flex flex-row widget summary balance">
            <div class="d-flex flex-column justify-content-center p-5">
                <i class="fa-solid fa-dollar-sign fa-2xl"></i>
            </div>
            <div class="d-flex flex-column m-auto py-3">
                <span class="lead">Balance</span>
                <h1 class="display-6">@ViewBag.Balance</h1>
            </div>
        </div>
    </div>
</div>

<!--Selected Dates-->
<div class="row mb-4">
    <div class="col-md-5">
        <div class="widget chart">
            <div class="p-4">
                <h3 class="fw-bold"> Date Selected:</h3>
                <p class="lead"> @ViewBag.StartDate <i class="bi bi-arrow-right-short"></i> @ViewBag.EndDate </p>
            </div>
        </div>
    </div>
    <div class="col-md-7">
        <div class="widget chart">
            <div class="p-4">
                <form asp-action="Index" method="post" class="row d-flex justify-content-around align-items-center">
                    <div class="mb-2 col-md-5">
                        <label asp-for="StartDate" class="form-label"></label>
                        <input asp-for="StartDate" type="date" class="form-control bg-dark text-white text-center" value="23/09/2022" />
                        <span asp-validation-for="StartDate" class="text-danger" style="font-size:small"></span>
                    </div>

                    <div class="mb-2 col-md-5">
                        <label asp-for="EndDate" class="form-label"></label>
                        <input asp-for="EndDate" type="date" class="form-control bg-dark text-white text-center" value="23/09/2022" />
                        <span asp-validation-for="EndDate" class="text-danger" style="font-size:small"></span>
                    </div>

                    <div class="mb-2 col-md-2">
                        <button type="submit" class="btn btn-outline-light fw-bold">Filter</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!--doughnut-->
<div class="row mb-4">
    <div class="col-md-4">
        <div class="widget chart">
            <div class="p-4">
                <h3 class="fw-bold"> Expenses by Category</h3>
            </div>
            <ejs-accumulationchart id="doughnutchart" enableSmartLabels background="#1a222b">
                <e-accumulation-series-collection>
                    <e-accumulation-series dataSource=@ViewBag.DoughnutChart xName="categoryTitleWithIcon" yName="amount" 
                    innerRadius="50%" legendShape="Circle">
                        <e-accumulationseries-datalabel name="formattedAmount" visible>
                        </e-accumulationseries-datalabel>
                    </e-accumulation-series>
                </e-accumulation-series-collection>
                <e-accumulationchart-legendsettings position="Top" toggleVisibility="false">
                    <e-legendsettings-textstyle color="#fff" size="1rem"></e-legendsettings-textstyle>
                </e-accumulationchart-legendsettings>
                <e-accumulationchart-tooltipsettings enable></e-accumulationchart-tooltipsettings>
            </ejs-accumulationchart>
        </div>
    </div>

    <!--Line chart-->
    <div class="col-md-8">
        <div class="widget chart">
            <div class="d-flex flex-row justify-content-between p-4">
                <h3 class="fw-bold">Income vs Expense</h3>

                <form asp-action="More" method="post" class="row d-flex justify-content-around align-items-center">
                    <input type="hidden" asp-for="StartDate" />
                    <input type="hidden" asp-for="EndDate" />
                    <button type="submit" class="btn btn-outline-light fw-bold">View More</button>

                    @*<a asp-action="More" asp-controller="Dashboard" class="btn btn-outline-light fw-bold">View More</a>*@
                </form>
            </div>
            <ejs-chart id="dashedLineContainer" palettes=@(new string[]{ "#65da41","#ff4e48" })>
     
                <e-chart-tooltipsettings enable="true" shared="true">
                </e-chart-tooltipsettings>
                <e-chart-primaryxaxis valueType="Category">                                                                                                                                                                                             
                    <e-majorgridlines width="0"></e-majorgridlines>
                    <e-majorticklines width="0"></e-majorticklines>
                </e-chart-primaryxaxis>
                <e-chart-primaryyaxis >
                    <e-majorgridlines width="1" color="#32414d" dashArray="3,5"></e-majorgridlines>
                    <e-majorticklines width="0"></e-majorticklines>
                    <e-linestyle width="0"></e-linestyle>
                </e-chart-primaryyaxis>
                <e-chart-chartarea>
                    <e-chartarea-border width="0"></e-chartarea-border>
                </e-chart-chartarea>
                <e-chart-crosshairsettings enable=true lineType="Vertical">
                    <e-crosshairsettings-line color="rgba(204,214,235,0.25)" width="20"></e-crosshairsettings-line>
                </e-chart-crosshairsettings>
                <e-series-collection>
                    <e-series dataSource="@ViewBag.LineChartData" xName="Day" yName="Income" name="Income" type="@Syncfusion.EJ2.Charts.ChartSeriesType.Spline"
                              width="3">
                        @*<e-series-marker visible="true" height="10" width="10"></e-series-marker>*@
                    </e-series>
                    <e-series dataSource="@ViewBag.LineChartData" xName="Day" yName="Expense" name="Expense" type="@Syncfusion.EJ2.Charts.ChartSeriesType.Spline"
                              width="3">
                        @*<e-series-marker visible="true" height="10" width="10" shape="Diamond"></e-series-marker>*@
                    </e-series>
                </e-series-collection>
                <e-chart-legendsettings position="Top" alignment="Far" toggleVisibility="true">
                    <e-legendsettings-textstyle color="#fff" size="1rem"></e-legendsettings-textstyle>
                </e-chart-legendsettings>
            </ejs-chart>

        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="widget">
            <div class="d-flex flex-row justify-content-between p-4">
                <h3>Recent Transactions</h3>
                <a asp-controller="Transaction" asp-action="Create" class="btn btn-outline-light fw-bold">Add transaction</a>
            </div>
            <div class="pb-4 px-4">
                <ejs-grid id="recent-transaction" dataSource="@ViewBag.RecentTransaction" gridLines="None">
                    <e-grid-columns>
                        <e-grid-column headerText="Category" field="CategoryWithIcon"></e-grid-column>
                        <e-grid-column headerText="Date" field="Date" type="date" format="dd-MMM-yy" textAlign="Left" width="120px"></e-grid-column>
                        <e-grid-column headerText="Amount" field="FormattedAmount" textAlign="Left" width="120px"></e-grid-column>
                    </e-grid-columns>
                </ejs-grid>
            </div>
        </div>
    </div>

    <div class="col-md-6">
        <div class="widget">
            <div class="p-4">
                <h3>Highest Transactions</h3>
            </div>
            <div class="pb-4 px-4">
                <ejs-grid id="highest-transaction" dataSource="@ViewBag.HighestTransaction" gridLines="None">
                    <e-grid-columns>
                        <e-grid-column headerText="Category" field="CategoryWithIcon"></e-grid-column>
                        <e-grid-column headerText="Date" field="Date" type="date" format="dd-MMM-yy" textAlign="Left" width="120px"></e-grid-column>
                        <e-grid-column headerText="Amount" field="FormattedAmount" textAlign="Left" width="120px"></e-grid-column>
                    </e-grid-columns>
                </ejs-grid>
            </div>
        </div>
    </div>
</div>